### ISSUE TITLE
火狐商店版本只有谷歌搜索才有

### ISSUE THREAD

**Issue by bfqbpq567** [josStorer/chat-gpt-search-engine-extension#2]
在火狐商店安装的扩展好像只有谷歌搜索界面才有chatgpt，和作者大大的不一样。只是安装商店版本的，其他主流搜索引擎没有chatgpt出现。

**Comment by bfqbpq567** [comment]
josc146大大，还有就是，火狐用临时安装扩展，退出浏览器或关机重启，扩展就会被删除了。火狐扩展搞成xpi格式安装会稳定些。要是能直接上架火狐商店就更好了，可惜是商店版本的只有谷歌搜索引擎才有。从商店安装的，同步可以同步扩展。

**Comment by josStorer** [comment]
商店上架的是原始项目, 我并没有上架, 但是火狐插件如果要避免临时安装, 必须要上传由火狐签名, 这最好由原始项目去做

我更倾向于将我的修改合并到原项目, 借了原项目的基础, 自己仅仅加了多搜索引擎支持就上架商店, 感觉有些不道德, 我不希望和原项目形成一种分裂

**Comment by josStorer** [comment]
目前原始项目已经合并了我提交的PR, 后续应该不久会发布, 届时就没有问题了

**Comment by bfqbpq567** [comment]
> 商店上架的是原始项目, 我并没有上架, 但是火狐插件如果要避免临时安装, 必须要上传由火狐签名, 这最好由原始项目去做
> 
> 我更倾向于将我的修改合并到原项目, 借了原项目的基础, 自己仅仅加了多搜索引擎支持就上架商店, 感觉有些不道德, 我不希望和原项目形成一种分裂

**Comment by bfqbpq567** [comment]
好的。Thanks♪(･ω･)ﾉ

**Comment by bfqbpq567** [comment]
已经可以了。

**Comment by josStorer** [comment]
@bfqbpq567 新版本已上线火狐商店: https://addons.mozilla.org/firefox/addon/chatgptbox/
火狐浏览器安卓版安装方式: https://github.com/josStorer/chatGPTBox/wiki/Install#install-to-android
